import './style.css'
import './components/profile-view.js'
import './components/projects-view.js'
import './components/skills-view.js'
import './components/contact-view.js'
import './interactions.js'
